# Generated by Django 5.1.2 on 2024-11-04 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="balance",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="balance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_1__lt", models.F("user_2"))),
                fields=("user_1", "user_2"),
                name="unique_user_pair",
            ),
        ),
    ]
